name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Install Composer dependencies
      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      # Set up AWS CLI for EC2 access
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Deploy the application to EC2
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i "${{ secrets.AWS_SSH_PRIVATE_KEY }}" ec2-user@${{ secrets.AWS_INSTANCE_IP }} "
          cd /home/ec2-user/playlist-app && \
          git pull && \
          composer install --no-dev --prefer-dist --optimize-autoloader && \
          php artisan migrate --force && \
          php artisan optimize
          "
